"""Change Datetime to String

Revision ID: 66667e9ede2d
Revises: bd850a5a84fd
Create Date: 2019-01-31 13:29:46.060616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66667e9ede2d'
down_revision = 'bd850a5a84fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_event_datetime'), 'event', ['datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_datetime'), table_name='event')
    # ### end Alembic commands ###
