"""empty message

Revision ID: bd850a5a84fd
Revises: 46f9cd4e9f45
Create Date: 2019-01-24 13:13:50.953488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd850a5a84fd'
down_revision = '46f9cd4e9f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_session_datetime'), 'session', ['datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_datetime'), table_name='session')
    # ### end Alembic commands ###
